version: "3.7"
services:
  mongo:
    container_name: mongodb
    image: "mongo"
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always
  api:
    container_name: api
    build: 
        context: ./backend
        dockerfile: Dockerfile
    ports:
        - "5000:5000"
    restart: always
    env_file:
      - backend/.env

    depends_on: 
        - mongo
  # client:
  #   container_name: client
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   restart: always

