version: "3.7"
services:
  mongo:
    container_name: mongodb

    image: "mongo"
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    restart: always
    # command: "--bind_ip_all --replSet rs0"
  api:
    container_name: api
    build: 
        context: ./backend
        dockerfile: Dockerfile
    # command: flask run
    ports:
        - "5000:5000"
    restart: always

    # environment:
    #     MONGODB_HOST: mongodb
    #     MONGODB_USERNAME: "apiuser"
    #     MONGODB_PASSWORD: "apipassword"
    depends_on: 
        - mongo
  client:
    container_name: client
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always

